sudo: required

language: minimal

services: docker

before_install:
  - docker -v

install:
  - travis_retry docker-compose pull
  - docker build -t digirati/ghent-madoc services/madoc
  - docker build -t digirati/ghent-madoc-db services/madoc-database

before_script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker-compose up -d
  - ./.travis/wait-for-omeka.sh

script:
  - .travis/test-script.sh

after_script:
  - docker-compose down

cache:
  bundler: true
  directories:
    - $HOME/docker
    - $HOME/.local

# Example of Docker deployment (push to docker + optional ECS)
deploy:
  # Publishing tags
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/ghent-madoc
    on:
      tags: true
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/ghent-madoc-db
    on:
      tags: true

if: |
  branch = master OR \
  type = pull_request OR \
  tag IS present
