version: "3"
services:
  madoc:
    build:
      context: services/madoc
    links:
      - madoc-database
    environment:
      - APP_ENV=${APP_ENV}
      - OMEKA__DATABASE_HOST=madoc-database
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=${MAIN_SITE_DOMAIN}
      - OMEKA__INTERNAL_URL=${OMEKA_INTERNAL_URL}
    ports:
      - "8898:80"
    volumes:
      - ./services/madoc/ghent-madoc-theme:/srv/omeka/themes/ghent-madoc-theme:Z
      - ./services/madoc/translations/s:/srv/omeka/translations/s:Z
      - ./var/files:/srv/omeka/files:Z

  madoc-database:
    build:
      context: services/madoc-database
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
