version: "3"
services:

  # Internal services

  gateway:
    image: digirati/madoc-gateway-beta:545b783
    environment:
      - TYK_GW_STORAGE_HOST=gateway-redis
      - TYK_GW_SECRET=${GATEWAY_SECRET}
    ports:
      - "8898:8080"
    links:
      - sorting-room
      - madoc
      - gateway-redis
      - tasks-api
      - model-api

  madoc:
    build:
      context: services/madoc
    links:
      - madoc-database
    environment:
      - APP_ENV=${APP_ENV}
      - OMEKA__DATABASE_HOST=madoc-database
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=${MAIN_SITE_DOMAIN}
      - OMEKA__INTERNAL_URL=${OMEKA_INTERNAL_URL}
    volumes:
      - ./services/madoc/ghent-madoc-theme:/srv/omeka/themes/ghent-madoc-theme:Z
      - ./services/madoc/translations/s:/srv/omeka/translations/s:Z
      - ./var/files:/srv/omeka/files:Z

  tasks-api:
    image: digirati/madoc-tasks-api-beta:545b783
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=tasks_api
      - DATABASE_PORT=5432
      - DATABASE_USER=tasks_api
      - DATABASE_SCHEMA=public
      - DATABASE_PASSWORD=tasks_api_password
    restart: "always"
    links:
      - shared-postgres

  model-api:
    image: digirati/capture-models:v0.2.2
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=model_api
      - DATABASE_PORT=5432
      - DATABASE_USER=model_api
      - DATABASE_SCHEMA=public
      - DATABASE_PASSWORD=model_api_password
    restart: "always"
    links:
      - shared-postgres

  shared-postgres:
    image: digirati/madoc-shared-postgres-beta:545b783
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - TASKS_API_PASSWORD=tasks_api_password
      - MODEL_API_PASSWORD=model_api_password
    volumes:
      - ./var/shared-database:/var/lib/postgresql/data:Z

  sorting-room:
    image: digirati/madoc-sorting-room-beta:545b783

  gateway-redis:
    image: redis:4.0-alpine

  madoc-database:
    build:
      context: services/madoc-database
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    volumes:
      - ./var/mysql:/var/lib/mysql:Z
