version: '3'
services:     
  madoc:
    image: digirati/madoc-platform:latest
    links:
      - madoc-database
    environment:
      - APP_ENV=PROD
      - OMEKA__DATABASE_HOST=omeka_db
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=${MADOC_DOMAIN}
    ports:
      - "80:80"
    volumes:
      - /opt/data/omeka_files:/srv/omeka/files:Z

  madoc-database:
    container_name: omeka_db
    image: digirati/madoc-platform-db:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - /opt/data/mysql_data:/var/lib/mysql:Z