# This is a pre-release
FROM digirati/madoc-platform-beta:a95b720

# Add our theme
ADD --chown=www-data:www-data ghent-madoc-theme /srv/omeka/themes/ghent-madoc-theme

# Add custom translations
ADD --chown=www-data:www-data translations /srv/omeka/translations/s/

# Add any other configuration needed.
